"""Static HTML brief rendering. One page, no JavaScript, evidence spans
highlighted and linked to their document anchors. Renders correctly with
zero, one, or many items — the layout is data-driven, not padded.
"""

import html as html_mod

from fi_intel.agents.brief import Brief


def _highlight(excerpt: str, needle: str) -> str:
    """Wrap the first case-insensitive occurrence of needle in <mark>."""
    esc_excerpt = html_mod.escape(excerpt)
    idx = excerpt.lower().find(needle.lower())
    if idx < 0:
        return esc_excerpt
    return (
        esc_excerpt[:idx]
        + "<mark>"
        + esc_excerpt[idx : idx + len(needle)]
        + "</mark>"
        + esc_excerpt[idx + len(needle) :]
    )


def render_html(brief: Brief) -> str:
    """Render the brief to a standalone HTML page."""
    esc = html_mod.escape
    date = brief.as_of.date().isoformat()
    parts: list[str] = []
    parts.append(
        "<!DOCTYPE html><html><head><meta charset='utf-8'>"
        f"<title>FI Brief — {esc(brief.desk)} — {date}</title>"
        "<style>body{font-family:system-ui,sans-serif;max-width:60em;margin:2em auto;color:#111}"
        ".item{border:1px solid #ccc;border-radius:6px;padding:1em;margin:1em 0}"
        ".meta{color:#555;font-size:.9em}mark{background:#ffe58f}"
        ".empty{color:#555}</style></head><body>"
    )
    parts.append(f"<h1>FI Daily Brief — {esc(brief.desk)}</h1>")
    parts.append(f"<p class='meta'>As of {date}</p>")

    if brief.nothing_material or not brief.items:
        parts.append(
            "<p class='empty'>No material developments for this desk in the "
            "coverage window. (This is a valid outcome, not a failure.)</p>"
        )
        parts.append("</body></html>")
        return "".join(parts)

    for item in brief.items:
        sig = item.signal
        opp = item.opportunity
        parts.append("<div class='item'>")
        # Title already names the situation; the pattern goes in the meta line.
        parts.append(f"<h2>{esc(opp.title)}</h2>")
        parts.append(
            f"<p class='meta'>{esc(sig.entity_name)} — pattern "
            f"{esc(sig.pattern)} (priority {sig.priority})</p>"
        )
        parts.append(f"<p>{esc(opp.summary)}</p>")
        parts.append(f"<p class='meta'><em>Falsifier:</em> {esc(opp.falsifier)}</p>")
        if item.evidence:
            parts.append("<h3>Evidence</h3><ul>")
            for ev in item.evidence:
                # Highlight the entity name within the cited span; link to the
                # document anchor so a reviewer can jump to the source.
                doc_anchor = f"doc-{esc(ev.source_id)}-{esc(ev.doc_id)}"
                shown = _highlight(ev.excerpt, sig.entity_name)
                parts.append(
                    f"<li><a href='#{doc_anchor}'>{esc(ev.evidence_id)}</a>: "
                    f"{shown}</li>"
                )
            parts.append("</ul>")
        parts.append("</div>")

    parts.append("<footer class='meta'>Generated by fi-intel. "
                 f"Deep-research cost: {brief.deep_research_cost:.0f}.</footer>")
    parts.append("</body></html>")
    return "".join(parts)
