"""Versioned evidence-ledger foundation.

The existing pipeline remains operational while callers migrate to these
models and repository contracts. PostgreSQL is the source of truth; graph and
search stores are projections of accepted assertions and signal transitions.
"""

from fi_intel.ledger.models import (
    AccessPolicy,
    AssertionObject,
    ClaimCandidate,
    ClaimDecision,
    ClaimDecisionType,
    ClaimObject,
    ClaimObjectKind,
    DocumentIdentity,
    DocumentVersion,
    EntityIdentity,
    EntityLinkDecision,
    EntityLinkStatus,
    EvidenceSpan,
    IntelligenceAssertion,
    Mention,
    MentionKind,
    OutboxEvent,
    PolicyLineage,
    RawAsset,
    SignalIdentity,
    SignalStatus,
    SignalTransition,
    derive_access_policy,
    document_identity_id,
    document_version_id,
    entity_link_identity_id,
    outbox_event_id,
    raw_asset_id,
    signal_identity_id,
)
from fi_intel.ledger.repository import (
    InMemoryIntelligenceLedger,
    IntelligenceLedger,
    LedgerConflictError,
    LedgerInvariantError,
    PostgresIntelligenceLedger,
)

__all__ = [
    "AccessPolicy",
    "AssertionObject",
    "ClaimCandidate",
    "ClaimDecision",
    "ClaimDecisionType",
    "ClaimObject",
    "ClaimObjectKind",
    "DocumentIdentity",
    "DocumentVersion",
    "EntityIdentity",
    "EntityLinkDecision",
    "EntityLinkStatus",
    "EvidenceSpan",
    "InMemoryIntelligenceLedger",
    "IntelligenceAssertion",
    "IntelligenceLedger",
    "LedgerConflictError",
    "LedgerInvariantError",
    "Mention",
    "MentionKind",
    "OutboxEvent",
    "PolicyLineage",
    "PostgresIntelligenceLedger",
    "RawAsset",
    "SignalIdentity",
    "SignalStatus",
    "SignalTransition",
    "derive_access_policy",
    "document_identity_id",
    "document_version_id",
    "entity_link_identity_id",
    "outbox_event_id",
    "raw_asset_id",
    "signal_identity_id",
]
